version: '3.8'

services:
  api:
    build: .
    container_name: glow-beauty-api
    ports:
      - "${PORT:-8085}:${PORT:-8085}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8085}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
